# UFSIT SCORINGENGINE (TM) CONFIG 
# https://github.com/scoringengine/scoringengine
#
# remember that this file must be renamed and placed in bin/competition.yaml to work with the scoring engine
#              _  _
#    _ _      (0)(0)-._  _.-'^^'^^'^^'^^'^^'--.
#   (.(.)----'`        ^^'                /^   ^^-._
#   (    `                 \             |    _    ^^-._
#    VvvvvvvVv~~`__,/.._>  /:/:/:/:/:/:/:/\  (_..,______^^-.
#  jgs  `^^^^^^^^`/  /   /  /`^^^^^^^^^>^^>^`>  >        _`)  )
#              (((`   (((`          (((`  (((`        `'--'^
---
teams:
- name: WhiteTeam
  color: White
  users:
  - username: whiteteam
    password: epicpassword123
- name: RedTeam
  color: Red
  users:
  - username: redteam
    password: epicpassword123
- name: ufsit
  color: Blue
  users:
  - username: blue
    password: shreksopwnd
  services:
  - name: QuasarLoud-ICMP
    check_name: ICMPCheck
    host: 10.13.37.4
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: ThirdImpact-ICMP
    check_name: ICMPCheck
    host: 10.13.37.6
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: Tokyo3-ICMP
    check_name: ICMPCheck
    host: 10.13.37.9
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: BlackMoon-ICMP
    check_name: ICMPCheck
    host: 10.13.37.10
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: Lilith-ICMP
    check_name: ICMPCheck
    host: 10.13.37.61
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: Rebirth-ICMP
    check_name: ICMPCheck
    host: 10.13.37.123
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: Vegetable-ICMP
    check_name: ICMPCheck
    host: 10.13.37.222
    port: 0
    points: 25
    environments:
    - matching_content: 1 packets transmitted, 1 received
  - name: QuasarLoud-SSH
    check_name: SSHCheck
    host: 10.13.37.4
    port: 22
    points: 150
    accounts:
    - username: melissa.chen
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: commands
        value: id;ls -l /home
    - matching_content: PID
      properties:
      - name: commands
        value: ps
  - name: BlackMoon-SSH
    check_name: SSHCheck
    host: 10.13.37.10
    port: 22
    points: 150
    accounts:
    - username: maxwell.starling
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: commands
        value: id;ls -l /home
    - matching_content: PID
      properties:
      - name: commands
        value: ps
  - name: Lilith-SSH
    check_name: SSHCheck
    host: 10.13.37.61
    port: 22
    points: 150
    accounts:
    - username: alan.chen
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: commands
        value: id;ls -l /home
    - matching_content: PID
      properties:
      - name: commands
        value: ps
  - name: Vegetable-SSH
    check_name: SSHCheck
    host: 10.13.37.222
    port: 22
    points: 150
    accounts:
    - username: john.taylor
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: commands
        value: id;ls -l /home
    - matching_content: PID
      properties:
      - name: commands
        value: ps
  - name: QuasarLoud-HTTP # not configured by default
    check_name: HTTPCheck
    host: 10.13.37.4
    port: 80
    points: 100
    environments:
    - matching_content: ABC123
      properties:
      - name: useragent
        value: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
      - name: vhost
        value: testbed_web
      - name: uri
        value: "/"
  - name: Vegetable-MySQL # not configured by default
    check_name: MYSQLCheck
    host: 10.13.37.222
    port: 3306
    points: 100
    accounts:
    - username: anna.wilson # You may have to create this user locally OR find a way to use LDAP/AD auth with MySQL
      password: Congratulations21
    environments:
    - matching_content: USER_PRIVILEGES
      properties:
      - name: database
        value: information_schema
      - name: command
        value: show tables;
  - name: Lilith-FTP # not configured by default
    check_name: FTPCheck
    host: 10.13.37.61
    port: 21
    points: 150
    accounts:
    - username: matthew.taylor # You may have to create this user locally OR find a way to use LDAP/AD auth for FTP
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: remotefilepath
        value: "/ftp_files/testfile.txt"
      - name: filecontents
        value: ABC123
  - name: ThirdImpact-SMB # not configured by default
    check_name: SMBCheck
    host: 10.13.37.6
    port: 445
    points: 100
    accounts:
    - username: jeremy.rover
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: remote_name
        value: COMPUTERNAME
      - name: share
        value: ScoredShare
      - name: file
        value: flag.txt
      # SHA256 hash of file
      - name: hash
        value: 3ac8347c1130bd1ffe9078f99be6cb690baedd9e5552de0f7140c0daded7e1fa
  - name: ThirdImpact-DNS # may be configured by default
    check_name: DNSCheck
    host: 10.13.37.6
    port: 53
    points: 100
    environments:
    - matching_content: 'status: NOERROR'
      properties:
      - name: qtype
        value: A
      - name: domain
        value: nerv.ccdc
  - name: Lilith-PostgreSQL # not configured 
    check_name: POSTGRESQLCheck
    host: 10.13.37.61
    port: 5432
    points: 100
    accounts:
    - username: william.wilson # You may have to create this user locally OR find a way to use LDAP/AD auth for PostreSQL
      password: Congratulations21
    environments:
    - matching_content: You are connected to database
      properties:
      - name: database
        value: testdb
      - name: command
        value: "\\conninfo"
  # - name: AGENT
  #   check_name: AgentCheck
  #   host: testbed_icmp
  #   port: 0
  #   points: 25
  #   environments:
  #     - matching_content: SUCCESS
  - name: ThirdImpact-WinRM
    check_name: WinRMCheck
    host: 10.13.37.6
    port: 0
    points: 100
    accounts:
    - username: jack.harris
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: commands
        value: ipconfig /all;whoami
  - name: Tokyo3-WinRM
    check_name: WinRMCheck
    host: 10.13.37.9
    port: 0
    points: 100
    accounts:
    - username: shinji.ikari
      password: Congratulations21
    environments:
    - matching_content: "^SUCCESS"
      properties:
      - name: commands
        value: ipconfig /all;whoami
  - name: ThirdImpact-RDP
    check_name: RDPCheck
    host: 10.13.37.6
    port: 3390
    points: 100
    accounts:
    - username: jeremy.rover
      password: Congratulations21
    environments:
    - matching_content: SUCCESS$
  - name: Tokyo3-RDP
    check_name: RDPCheck
    host: 10.13.37.9
    port: 3390
    points: 100
    accounts:
    - username: william.wilson
      password: Congratulations21
    environments:
  - name: Rebirth-RDP
    check_name: RDPCheck
    host: 10.13.37.123
    port: 3390
    points: 100
    accounts:
    - username: alan.chen
      password: Congratulations21
    environments:
    - matching_content: SUCCESS$
  - name: ThirdImpact-LDAP
    check_name: LDAPCheck
    host: 10.13.37.6
    port: 389
    points: 50
    accounts:
    - username: maxwell.starling
      password: Congratulations21
    environments:
    - matching_content: "^result: 0 Success"
      properties:
      - name: domain
        value: nerv.ccdc
      - name: base_dn
        value: dc=nerv,dc=ccdc
flags:
  - type: file
    platform: nix
    perm: user
    data:
        path: "/tmp/flag"
        content: "hi"
