- name: enable and start wazuh agent
  listen: "Enable Wazuh service"
  when: ansible_facts['distribution'] != 'Alpine'
  ansible.builtin.service:
    enabled: true
    name: "wazuh-agent"
    state: "started"

- name: start wazuh if service failed
  listen: "Start Wazuh Agent manually"
  ansible.builtin.shell:
    cmd: "/var/ossec/bin/wazuh-control start"
  become: true
