# - name: Install and Configure Auditd
#   hosts: linux
#   become: yes
#   tasks:
#   - name: Enable internet access (Auditd)
#     ansible.builtin.script: enable_internet.sh

---
- name: Install and Configure Auditd
  hosts: linux
  become: true
  tasks:
    - name: Install Auditd
      block:
        - name: Install package auditd
          ansible.builtin.package:
            name: "auditd"
            state: "present"
      rescue:
        - name: Install package audit
          ansible.builtin.package:
            name: "audit"
            state: "present"

    - name: Install custom audit rules
      ansible.builtin.copy:
        src: "audit.rules"
        dest: "/etc/audit/rules.d/audit.rules"
        mode: '0644'
      notify: Restart Auditd


  handlers:
    - name: Restart Auditd
      ansible.builtin.service:
        name: "auditd"
        state: "restarted"
